services:
    bot:
        container_name: equmenia-bot
        build:
            context: ..
            dockerfile: docker/Dockerfile
        env_file:
            - ../.env
        volumes:
            - ../data:/app/data
        networks:
            - web
        restart: unless-stopped

networks:
    web:
        external: true
